name: bmiNew
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/bmi_logo.png"


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/bmi_logo.png
    - assets/cat2.jpg
    - assets/images/p1.jpg
    - assets/images/p2.jpg
    - assets/images/p3.jpg
    - assets/images/p4.jpg


